---
title: "pdf_output"
author: "Andrea Hofer"
date: "9/19/2017"
output: pdf_document
---

```{r setup, include=FALSE, message = FALSE, echo = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.pos = 'h')
```



```{r message = FALSE, echo = FALSE, warning = FALSE}
# This file creates histograms for all the questions in the data set
rm(list = ls())
```

```{r message = FALSE, echo = FALSE, warning = FALSE}
# Load libraries
library(lettercase)
library(ggplot2)
library(tibble)
library(readr)

library(dplyr)
library(tidyr)
library(janitor)
```


```{r message = FALSE, echo = FALSE, warning = FALSE}
# Load the data set
fy_df = read.table("./data_raw/fy_eval.csv", header = TRUE, sep = ",", check.names = FALSE, na.strings = c(""," ","NA"), stringsAsFactors = FALSE)



# Replace special characters 

# Replace weird characters that cannot be printed out by print

fy_df = data.frame(lapply(fy_df, gsub, pattern = "\n\n", replacement = " "), check.names = FALSE,  stringsAsFactors = FALSE)
fy_df = data.frame(lapply(fy_df, gsub, pattern = "%", replacement = " "), check.names = FALSE,  stringsAsFactors = FALSE)

## Now all the columns are strings and I need to convert the number ones back to integers:
# I will loop through all columns and check whether there is at least one letter, if there is not, it will be  
# converted to string
# This is done by checking for each cell whether there is a letter and if there is TRUE is added to the vector locigal for this cell
# Once we went through all the cells of one column, the vector logic is added up and if there was at least one letter, there will be at least one TRUE which will make the sum greater equal to 1
# So if the sum is zero, meaning there were no letters in this column, the column is made integer
logic = c()
sum = c()
for (i in 2:328) {
  for (j in 1:15) {
    logic[j] = grepl('[a-zA-Z]+', fy_df[[j,i]])
  }
  sum[i] = sum(logic)
  if (sum[i] > 0) {
    fy_df[[i]] = as.character(fy_df[[i]])
  } else {
    fy_df[[i]] = as.integer(as.character(fy_df[[i]]))
  }
}

 
```



```{r message = FALSE, echo = FALSE, warning = FALSE, results = "asis"}
# Loop over all variables to create a pdf with histograms and text output

# Note: if want to print them out separately, create an empty list before and save the plots in this list (for more
# information see: https://stackoverflow.com/questions/26034177/r-saving-multiple-ggplots-using-a-for-loop)
for (i in 2:20) {
  if (is.integer(fy_df[[i]])) {
    cat("## Statement: ", paste0(names(fy_df)[i]), "  \n")
    histogram = ggplot(data = fy_df) +
      geom_bar(mapping = aes(x = fy_df[[i]])) +
      labs(x = "Possible answers ranging from 1 to 5",
           y = "Count") +
      scale_x_continuous(breaks = c(1, 2, 3, 4, 5), limits = c(0.5,5.5)) +
      theme_bw()
    print(histogram)  
    cat("  \n")
  } else {
    cat("  \n###", paste0(names(fy_df)[i]), "  \n")
    for (j in 1:15) {
      if (!is.na(fy_df[[j,i]])) {
        cat(" * ", paste(fy_df[[j,i]]), "  \n")
      }
    }
  }
  cat("  \n")
}

```



